import { PrismaClient, ContentStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
import { readdir, stat } from "node:fs/promises";
import { extname, join } from "node:path";
import { defaultPageSections, defaultPageSectionZh } from "../lib/page-defaults";

const prisma = new PrismaClient();
const productFeatures = (a:string,b:string,c:string)=>JSON.stringify([{title:a,text:"Engineered for dependable daily performance."},{title:b,text:"Designed and verified by our product engineering team."},{title:c,text:"Ready for global OEM/ODM programs."},{title:"Multi-Protection",text:"Built-in safeguards for current, voltage, temperature and short circuit."},{title:"OEM Customization",text:"Logo, color, packaging and specifications tailored to your brand."}]);
const applications=JSON.stringify([{title:"On the Go",text:"Compact power wherever business takes you."},{title:"Travel Friendly",text:"Portable design for everyday travel."},{title:"Work & Productivity",text:"Reliable power through the workday."},{title:"Daily Convenience",text:"Simple, fast and secure charging."}]);
const faqs=JSON.stringify([{question:"Can this product be customized for our brand?",answer:"Yes. We support product color, logo, specifications, manuals and retail packaging customization."},{question:"What is the typical sample lead time?",answer:"Standard samples are normally prepared in 7–12 business days after specifications are confirmed."},{question:"Which certifications are available?",answer:"Certification depends on model and target market. Common files include CE, FCC, RoHS and UN38.3."}]);

async function main(){
  const permissionKeys=["*",...['products','news','pages','factory','quality','seo','settings','locales','inquiries','email','security','media'].flatMap((p)=>[`${p}.read`,`${p}.write`,`${p}.delete`])];
  const permissionMap=new Map<string,string>();
  for(const key of permissionKeys){const p=await prisma.permission.upsert({where:{key},update:{name:key},create:{key,name:key,description:`Server-side permission: ${key}`}});permissionMap.set(key,p.id)}
  const superRole=await prisma.role.upsert({where:{name:"超级管理员"},update:{description:"完整系统权限",isSystem:true},create:{name:"超级管理员",description:"完整系统权限",isSystem:true}});
  const contentRole=await prisma.role.upsert({where:{name:"内容管理员"},update:{description:"产品、新闻、页面、媒体与SEO"},create:{name:"内容管理员",description:"产品、新闻、页面、媒体与SEO"}});
  const salesRole=await prisma.role.upsert({where:{name:"销售管理员"},update:{description:"询盘、客户跟进与邮件"},create:{name:"销售管理员",description:"询盘、客户跟进与邮件"}});
  await prisma.rolePermission.deleteMany({where:{roleId:{in:[superRole.id,contentRole.id,salesRole.id]}}});
  await prisma.rolePermission.create({data:{roleId:superRole.id,permissionId:permissionMap.get("*")!}});
  for(const key of permissionKeys.filter((k)=>/^(products|news|pages|factory|quality|seo|media|locales)\./.test(k)))await prisma.rolePermission.create({data:{roleId:contentRole.id,permissionId:permissionMap.get(key)!}});
  for(const key of permissionKeys.filter((k)=>/^(inquiries|email)\./.test(k)))await prisma.rolePermission.create({data:{roleId:salesRole.id,permissionId:permissionMap.get(key)!}});
  const email=(process.env.DEFAULT_ADMIN_EMAIL||"admin@enercore.com").toLowerCase();const password=process.env.DEFAULT_ADMIN_PASSWORD||"ChangeMe123!";
  const admin=await prisma.user.upsert({where:{email},update:{name:"Shanze",isActive:true},create:{email,name:"Shanze",passwordHash:await bcrypt.hash(password,12),isActive:true}});
  await prisma.userRole.upsert({where:{userId_roleId:{userId:admin.id,roleId:superRole.id}},update:{},create:{userId:admin.id,roleId:superRole.id}});

  const settings=[['general','site_name','ENERCORE',true],['general','site_name_zh','能核科技',true],['general','site_tagline','POWERING YOUR LIFE',true],['general','site_tagline_zh','可靠能源，驱动未来',true],['general','logo_url','',true],['company','company_name','Enercore Technology Co., Ltd.',true],['company','company_name_zh','能核科技有限公司',true],['company','company_description','Professional OEM/ODM manufacturer of portable charging products, providing reliable solutions to customers worldwide.',true],['company','company_description_zh','专业便携充电产品 OEM/ODM 制造商，为全球客户提供可靠的充电解决方案。',true],['general','cta_title','Ready to Start Your Project?',true],['general','cta_title_zh','准备开始您的项目了吗？',true],['general','cta_description','Let’s build the right charging solution for your market.',true],['general','cta_description_zh','让我们为您的市场打造合适的充电解决方案。',true],['general','cta_label','Get a Quote Now',true],['general','cta_label_zh','立即获取报价',true],['contact','phone','+86 755 8888 9999',true],['contact','email','sales@enercore.com',true],['contact','address','Building A, No.168 Industrial Road, Shenzhen, Guangdong, China',true],['contact','address_zh','中国广东省深圳市工业路168号A栋',true],['company','founded','2012',true],['company','factory_area','20,000+ m²',true],['company','monthly_output','1,000,000+ pcs',true],['company','export_countries','100+',true]] as const;
  const normalizedSettings=settings.map((item)=>item[1]==='company_name'?[item[0],item[1],'Shanze New Energy Technology Co., Ltd.',item[3]] as const:item);
  for(const [group,key,value,isPublic] of normalizedSettings)await prisma.setting.upsert({where:{key},update:{group,isPublic},create:{group,key,value,isPublic}});
  const localeEn=await prisma.locale.upsert({where:{code:"en"},update:{name:"English",isDefault:true,isActive:true},create:{code:"en",name:"English",isDefault:true,isActive:true,sortOrder:1}});const localeZh=await prisma.locale.upsert({where:{code:"zh"},update:{name:"简体中文",isActive:true},create:{code:"zh",name:"简体中文",isActive:true,sortOrder:2}});
  const trZh=async(entityType:string,entityId:string,values:Record<string,string>)=>{for(const [field,value] of Object.entries(values))await prisma.translation.upsert({where:{localeId_entityType_entityId_field:{localeId:localeZh.id,entityType,entityId,field}},update:{value},create:{localeId:localeZh.id,entityType,entityId,field,value}})};
  const nav=[['Home','/',1],['About Us','/about',2],['Products','/products',3],['Factory','/factory',4],['Quality','/quality',5],['News','/news',6],['Contact','/contact',7]] as const;
  const navZh:Record<string,string>={Home:'首页','About Us':'关于我们',Products:'产品中心',Factory:'工厂实力',Quality:'品质保障',News:'新闻资讯',Contact:'联系我们'};
  for(const [label,href,sortOrder] of nav){const found=await prisma.navigationItem.findFirst({where:{href,location:"HEADER"}});const item=found?await prisma.navigationItem.update({where:{id:found.id},data:{label,sortOrder,isVisible:true}}):await prisma.navigationItem.create({data:{label,href,sortOrder,location:"HEADER"}});await prisma.translation.upsert({where:{localeId_entityType_entityId_field:{localeId:localeZh.id,entityType:'NavigationItem',entityId:item.id,field:'label'}},update:{value:navZh[label]},create:{localeId:localeZh.id,entityType:'NavigationItem',entityId:item.id,field:'label',value:navZh[label]}})}

  const banners=[
    {key:"home_hero",page:"home",title:"Reliable Manufacturing for Innovative",subtitle:"Charging Products",description:"Professional OEM/ODM service, strict quality control, and reliable global export experience.",image:"/references/home.png",ctaLabel:"Learn More",ctaHref:"/about"},
    {key:"about_hero",page:"about",title:"About Enercore",subtitle:"Your Trusted Partner in OEM/ODM",description:"We deliver innovative, reliable and high-quality charging solutions tailored to power your brand.",image:"/references/about.png",ctaLabel:"Contact Us",ctaHref:"/contact"},
    {key:"products_hero",page:"products",title:"Charging Products",subtitle:"for Global Markets",description:"Innovative, certified and reliable charging solutions engineered for performance, safety and design.",image:"/references/products.png",ctaLabel:"Get a Quote",ctaHref:"/contact#quote"},
    {key:"factory_hero",page:"factory",title:"Advanced",subtitle:"Manufacturing Facility",description:"State-of-the-art equipment, intelligent production systems and strict quality control.",image:"/references/factory.png",ctaLabel:"Start Your Project",ctaHref:"/contact"},
    {key:"quality_hero",page:"quality",title:"Strict Quality Control,",subtitle:"Reliable Performance",description:"A comprehensive quality management system from incoming materials to final delivery.",image:"/references/quality.png",ctaLabel:"Request Quality File",ctaHref:"/contact"},
    {key:"news_hero",page:"news",title:"News & Insights",subtitle:"Latest from ENERCORE",description:"Product updates, industry insights and company milestones from our global manufacturing team.",image:"/references/news.png",ctaLabel:"Contact Us",ctaHref:"/contact"},
    {key:"contact_hero",page:"contact",title:"Contact Us",subtitle:"We're Here to Power Your Business",description:"Share your charging product requirements and our team will reply within 24 hours.",image:"/references/contact.png",ctaLabel:"Send Inquiry",ctaHref:"#quote"},
  ];
  const bannerZh:Record<string,Record<string,string>>={home_hero:{title:'可靠制造，成就创新',subtitle:'充电产品',description:'专业 OEM/ODM 服务、严格质量控制与可靠的全球出口经验。',ctaLabel:'了解更多'},about_hero:{title:'关于能核科技',subtitle:'值得信赖的 OEM/ODM 合作伙伴',description:'为您的品牌提供创新、可靠、高品质的充电解决方案。',ctaLabel:'联系我们'},products_hero:{title:'充电产品',subtitle:'服务全球市场',description:'面向性能、安全与设计打造的创新、认证、可靠充电解决方案。',ctaLabel:'获取报价'},factory_hero:{title:'先进',subtitle:'智能制造基地',description:'先进设备、智能生产系统和严格质量控制。',ctaLabel:'启动您的项目'},quality_hero:{title:'严格质量控制',subtitle:'可靠性能保障',description:'从来料到最终交付的完整质量管理体系。',ctaLabel:'索取品质资料'},news_hero:{title:'新闻与洞察',subtitle:'能核科技最新动态',description:'来自全球制造团队的产品动态、行业洞察和公司里程碑。',ctaLabel:'联系我们'},contact_hero:{title:'联系我们',subtitle:'为您的业务持续赋能',description:'告诉我们您的充电产品需求，团队将在 24 小时内回复。',ctaLabel:'提交询盘'}};
  for(const banner of banners){const row=await prisma.banner.upsert({where:{key:banner.key},update:{...banner,status:ContentStatus.PUBLISHED},create:{...banner,status:ContentStatus.PUBLISHED}});await trZh('Banner',row.id,bannerZh[banner.key])}
  const pageData=[{slug:"about",title:"About ENERCORE",excerpt:"Your trusted OEM/ODM manufacturing partner.",content:"Since 2012, Enercore has grown from a dedicated charging accessories supplier into a trusted OEM/ODM manufacturing partner. We provide end-to-end solutions from industrial design and engineering to manufacturing and global delivery."},{slug:"privacy",title:"Privacy Policy",excerpt:"How we protect business contact information.",content:"We collect and process contact details only to respond to business inquiries, provide requested quotations and meet legal obligations."},{slug:"terms",title:"Terms of Use",excerpt:"Website terms.",content:"These terms govern access to and use of the ENERCORE website."}];
  for(const page of pageData)await prisma.page.upsert({where:{slug:page.slug},update:{...page,status:ContentStatus.PUBLISHED,publishedAt:new Date()},create:{...page,status:ContentStatus.PUBLISHED,publishedAt:new Date()}});

  const categoryData=[
    {name:"Magnetic Power Banks",slug:"magnetic-power-banks",description:"Snap, charge and go with high-capacity magnetic power banks."},
    {name:"Wireless Chargers",slug:"wireless-chargers",description:"Efficient wireless charging for phones, earbuds and smartwatches."},
    {name:"Charging Accessories",slug:"charging-accessories",description:"Cables, wall chargers and car chargers built for dependable use."},
    {name:"Gift Box Sets",slug:"gift-box-sets",description:"Premium packaged charging sets for retail and corporate gifting."},
    {name:"Custom OEM/ODM",slug:"custom-oem-odm",description:"Complete product design, engineering, branding and packaging programs."},
  ];
  const categoryZh:Record<string,{name:string,description:string}>={'magnetic-power-banks':{name:'磁吸充电宝',description:'大容量磁吸充电宝，轻轻一贴即可稳定快速充电。'},'wireless-chargers':{name:'无线充电器',description:'适用于手机、耳机与智能手表的高效无线充电方案。'},'charging-accessories':{name:'充电配件',description:'耐用可靠的数据线、墙充和车载充电器。'},'gift-box-sets':{name:'礼盒套装',description:'适合零售和企业礼赠的高品质充电套装。'},'custom-oem-odm':{name:'定制 OEM/ODM',description:'提供产品设计、工程、品牌和包装的一站式定制服务。'}};
  const cats:Record<string,string>={};for(let i=0;i<categoryData.length;i++){const item=categoryData[i];const row=await prisma.productCategory.upsert({where:{slug:item.slug},update:{...item,sortOrder:i+1,isVisible:true},create:{...item,sortOrder:i+1,isVisible:true}});cats[item.slug]=row.id;await trZh('ProductCategory',row.id,categoryZh[item.slug])}
  const specs=JSON.stringify({Model:"EC-MPB05K",Battery:"5000mAh / 3.85V",Wireless:"5W / 7.5W / 10W / 15W",Input:"USB-C PD 20W",Output:"USB-C PD 20W",Size:"99.5 × 65.5 × 9.6 mm",Material:"ABS + PC",Protection:"OCP, OVP, OTP, SCP",Certification:"CE, RoHS, FCC, UN38.3"});
  const products=[
    ["Magnetic Power Bank 10000mAh","magnetic-power-bank-10000","EC-MPB10K","magnetic-power-banks","15W Wireless","High Capacity","MagSafe Compatible",true],
    ["Magnetic Power Bank 5000mAh","magnetic-power-bank-5000","EC-MPB05K","magnetic-power-banks","Ultra Slim","15W Wireless","USB-C PD",true],
    ["3-in-1 Wireless Charger Stand","3-in-1-wireless-charger","EC-WCS31","wireless-chargers","Multi-Device","Foldable","Fast Charging",true],
    ["Magnetic Wireless Charger Pad","magnetic-wireless-pad","EC-WCP15","wireless-chargers","15W Max","Ultra Slim","Strong Magnetic",false],
    ["PD 20W Power Bank 20000mAh","pd-20w-power-bank","EC-PB20K","magnetic-power-banks","20W PD","LED Display","High Capacity",false],
    ["38W USB-C Car Charger","38w-usb-c-car-charger","EC-CC38","charging-accessories","PD 20W","QC 18W","Dual Port",false],
    ["GaN 65W Wall Charger","gan-65w-wall-charger","EC-GAN65","charging-accessories","GaN","PD 65W","Compact",true],
    ["USB-C to USB-C Cable 100W","usb-c-cable-100w","EC-C100","charging-accessories","100W PD","Nylon Braided","E-Marker",false],
    ["3-in-1 Travel Charging Kit","travel-charging-kit","EC-TCK31","gift-box-sets","Universal","Compact","Travel Ready",false],
    ["Premium Gift Set 3-in-1","premium-gift-set","EC-GS31","gift-box-sets","Premium Packaging","Best Seller","Customizable",true],
  ] as const;
  const productNamesZh:Record<string,string>={'magnetic-power-bank-10000':'磁吸充电宝 10000mAh','magnetic-power-bank-5000':'磁吸充电宝 5000mAh','3-in-1-wireless-charger':'三合一无线充电支架','magnetic-wireless-pad':'磁吸无线充电板','pd-20w-power-bank':'PD 20W 充电宝 20000mAh','38w-usb-c-car-charger':'38W USB-C 车载充电器','gan-65w-wall-charger':'GaN 65W 墙充','usb-c-cable-100w':'USB-C 转 USB-C 100W 数据线','travel-charging-kit':'三合一旅行充电套装','premium-gift-set':'精品三合一礼盒套装'};
  const specsZh=JSON.stringify({'型号':'EC-MPB05K','电池容量':'5000mAh / 3.85V','无线输出':'5W / 7.5W / 10W / 15W','输入':'USB-C PD 20W','有线输出':'USB-C PD 20W','尺寸':'99.5 × 65.5 × 9.6 mm','材质':'ABS + PC','安全保护':'过流、过压、过温、短路保护','认证':'CE、RoHS、FCC、UN38.3'});
  const featuresZh=JSON.stringify([{title:'性能可靠',text:'为日常稳定使用而精心设计。'},{title:'工程验证',text:'由产品工程团队完成设计与验证。'},{title:'支持定制',text:'支持面向全球市场的 OEM/ODM 项目。'},{title:'多重保护',text:'内置电流、电压、温度和短路保护。'},{title:'OEM 定制',text:'可按品牌定制标志、颜色、包装和规格。'}]);
  const applicationsZh=JSON.stringify([{title:'移动使用',text:'随时随地提供轻巧可靠的电力。'},{title:'旅行便携',text:'便携设计适合日常差旅。'},{title:'办公效率',text:'为全天工作提供稳定电力。'},{title:'日常便利',text:'简单、快速且安全的充电体验。'}]);
  const faqsZh=JSON.stringify([{question:'可以定制成我们的品牌吗？',answer:'可以。支持产品颜色、Logo、规格、说明书和零售包装定制。'},{question:'样品交期通常多久？',answer:'规格确认后，标准样品通常在 7–12 个工作日内完成。'},{question:'可以提供哪些认证？',answer:'认证取决于型号和目标市场，常见文件包括 CE、FCC、RoHS 和 UN38.3。'}]);
  for(let i=0;i<products.length;i++){const [name,slug,sku,cat,a,b,c,featured]=products[i];const row=await prisma.product.upsert({where:{slug},update:{name,sku,categoryId:cats[cat],status:ContentStatus.PUBLISHED,isFeatured:featured,sortOrder:i+1},create:{name,slug,sku,categoryId:cats[cat],tagline:"Wireless. Efficient. Built for global brands.",summary:`${name} combines dependable performance, certified safety and a refined design for retail and OEM programs.`,description:`A production-ready ${name} developed for brands, distributors and corporate programs. Specifications, colors, packaging and compliance can be tailored to target markets.`,specifications:specs,features:productFeatures(a,b,c),applications,faqs,status:ContentStatus.PUBLISHED,isFeatured:featured,sortOrder:i+1,publishedAt:new Date()}});const zhName=productNamesZh[slug];await trZh('Product',row.id,{name:zhName,tagline:'无线高效，为全球品牌而打造。',summary:`${zhName}兼具可靠性能、认证安全与精致设计，适合零售和 OEM 项目。`,description:`面向品牌商、经销商和企业项目打造的量产级${zhName}，规格、颜色、包装和合规方案均可按目标市场定制。`,specifications:specsZh,features:featuresZh,applications:applicationsZh,faqs:faqsZh})}

  const newsCategories=[['Product Launches','product-launches'],['Company Updates','company-updates'],['Factory Updates','factory-updates'],['Trade Shows','trade-shows'],['Industry Insights','industry-insights']] as const;const newsCategoryZh:Record<string,string>={'product-launches':'产品发布','company-updates':'公司动态','factory-updates':'工厂动态','trade-shows':'展会活动','industry-insights':'行业洞察'};const nCats:Record<string,string>={};for(let i=0;i<newsCategories.length;i++){const [name,slug]=newsCategories[i];const c=await prisma.newsCategory.upsert({where:{slug},update:{name,sortOrder:i+1},create:{name,slug,sortOrder:i+1}});nCats[slug]=c.id;await trZh('NewsCategory',c.id,{name:newsCategoryZh[slug]})}
  const posts=[
    ["Next-Gen MagSafe Power Bank Series Redefines Portable Charging","next-gen-magsafe-power-bank","product-launches"],
    ["Factory Expansion Update: New Intelligent Production Line Now Operational","factory-expansion-intelligent-line","factory-updates"],
    ["Qi2 Certified Wireless Charger Collection Officially Launched","qi2-certified-wireless-charger","product-launches"],
    ["ENERCORE Showcases Innovative Charging Solutions at Global Sources","global-sources-showcase","trade-shows"],
    ["ENERCORE Gives Back: Community Tree Planting Day","community-tree-planting","company-updates"],
    ["GaN Technology: Powering the Future of Fast Charging","gan-technology-fast-charging","industry-insights"],
    ["New 10000mAh Magnetic Power Bank Now Available","new-10000mah-magnetic-power-bank","product-launches"],
    ["Quality First: Our 6-Layer Quality Control Process","six-layer-quality-control","factory-updates"],
    ["Industry Insight: The Future of Wireless Charging","future-wireless-charging","industry-insights"],
  ] as const;
  const postTitlesZh:Record<string,string>={'next-gen-magsafe-power-bank':'新一代 MagSafe 充电宝系列重新定义便携充电','factory-expansion-intelligent-line':'工厂扩建：全新智能生产线正式投产','qi2-certified-wireless-charger':'Qi2 认证无线充电器系列正式发布','global-sources-showcase':'能核科技亮相环球资源展，展示创新充电方案','community-tree-planting':'能核科技公益植树活动','gan-technology-fast-charging':'GaN 技术：快充的未来动力','new-10000mah-magnetic-power-bank':'全新 10000mAh 磁吸充电宝上市','six-layer-quality-control':'品质优先：六层质量控制流程','future-wireless-charging':'行业洞察：无线充电的未来'};
  for(let i=0;i<posts.length;i++){const [title,slug,cat]=posts[i];const row=await prisma.news.upsert({where:{slug},update:{title,status:ContentStatus.PUBLISHED},create:{title,slug,categoryId:nCats[cat],excerpt:"Discover the people, engineering and systems behind ENERCORE's latest manufacturing and product development milestone.",content:"ENERCORE continues to invest in reliable engineering, transparent quality systems and responsive service for global B2B customers.\n\nThis update highlights the work of our product, manufacturing and customer teams as we help brands bring safe and competitive charging products to market. Contact our sales team for technical files, samples and project support.",isFeatured:i===0,status:ContentStatus.PUBLISHED,publishedAt:new Date(Date.now()-i*7*86400_000)}});await trZh('News',row.id,{title:postTitlesZh[slug],excerpt:'了解能核科技最新制造与产品开发里程碑背后的团队、工程和系统。',content:'能核科技持续投资可靠工程、透明质量体系和快速响应服务，为全球 B2B 客户创造价值。\n\n本次更新展示了产品、制造和客户团队的工作成果。我们帮助品牌将安全、有竞争力的充电产品推向市场，欢迎联系销售团队获取技术资料、样品和项目支持。'})}

  const equipment=[['SMT Production Line','High-speed placement with SPI, AOI and automated traceability.'],['Wave Soldering Machine','Lead-free soldering with stable process control.'],['Assembly Line','Ergonomic stations and standardized work instructions.'],['Injection Molding','Precision molding for high-quality plastic components.'],['Testing Cabinets','Aging and performance testing for safety and reliability.'],['Packaging Line','Automated, secure and standardized packing.']];
  const oldEquipment=await prisma.factoryEquipment.findMany();if(!oldEquipment.length)for(let i=0;i<equipment.length;i++)await prisma.factoryEquipment.create({data:{name:equipment[i][0],description:equipment[i][1],sortOrder:i+1}});
  const workshops=[['Production Line','Automated and efficient manufacturing.'],['Workers in Uniform','Professional and standardized operations.'],['Inspection Area','Strict and accurate quality checks.'],['Packaging Area','Safe and well-organized fulfillment.'],['Warehouse','Neat, traceable inventory management.'],['Logistics & Loading','Organized loading and dispatch for reliable global delivery.']];for(let i=0;i<workshops.length;i++){const existing=await prisma.workshop.findFirst({where:{name:workshops[i][0]}});if(!existing)await prisma.workshop.create({data:{name:workshops[i][0],description:workshops[i][1],sortOrder:i+1}})}
  const certs=[['CE','Conformité Européenne'],['FCC','Federal Communications Commission'],['RoHS','Restriction of Hazardous Substances'],['3C','China Compulsory Certification'],['UN38.3','Transport Safety Certification']];for(let i=0;i<certs.length;i++){const existing=await prisma.certificate.findFirst({where:{name:certs[i][0]}});if(!existing)await prisma.certificate.create({data:{name:certs[i][0],issuer:certs[i][1],sortOrder:i+1}})}
  const equipmentZh=[['SMT 生产线','高速贴片，配备 SPI、AOI 和自动追溯。'],['波峰焊设备','无铅焊接与稳定工艺控制。'],['装配生产线','人体工学工位和标准化作业指导。'],['注塑成型','高品质塑胶零件精密成型。'],['老化测试柜','安全性与可靠性老化和性能测试。'],['自动包装线','自动、安全、标准化包装。']];const equipmentRows=await prisma.factoryEquipment.findMany({orderBy:{sortOrder:'asc'}});for(let i=0;i<equipmentRows.length&&i<equipmentZh.length;i++)await trZh('FactoryEquipment',equipmentRows[i].id,{name:equipmentZh[i][0],description:equipmentZh[i][1]});
  const workshopsZh=[['生产线','自动化高效制造。'],['标准着装员工','专业、标准化作业。'],['质量检验区','严格精准的质量检查。'],['包装区域','安全有序的交付作业。'],['仓库','整洁且可追溯的库存管理。'],['物流装运区','规范装载与发运，保障全球订单可靠交付。']];const workshopRows=await prisma.workshop.findMany({orderBy:{sortOrder:'asc'}});for(let i=0;i<workshopRows.length&&i<workshopsZh.length;i++)await trZh('Workshop',workshopRows[i].id,{name:workshopsZh[i][0],description:workshopsZh[i][1]});
  for(const section of defaultPageSections){let row=await prisma.pageSection.upsert({where:{page_key:{page:section.page,key:section.key}},update:{sortOrder:section.sortOrder},create:section});if(row.items==='[]'&&section.items!=='[]')row=await prisma.pageSection.update({where:{id:row.id},data:{items:section.items}});await trZh('PageSection',row.id,defaultPageSectionZh[`${section.page}:${section.key}`]||{})}
  const routes=[['/','ENERCORE | OEM/ODM Charging Products Manufacturer'],['/about','About ENERCORE'],['/products','Charging Products for Global Markets'],['/factory','Advanced Manufacturing Facility'],['/quality','Strict Quality Control'],['/news','News & Insights'],['/contact','Contact & Get a Quote']];for(const [route,title] of routes)await prisma.seoMeta.upsert({where:{route},update:{title},create:{route,title,description:"ENERCORE provides certified OEM/ODM charging products and reliable manufacturing service for global B2B customers.",canonical:`${process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000"}${route}`}});
  await prisma.emailTemplate.upsert({where:{key:"new_inquiry"},update:{name:"新询盘销售通知"},create:{key:"new_inquiry",name:"新询盘销售通知",subject:"New website inquiry {{referenceNo}} — {{companyName}}",html:"<h2>New B2B Inquiry {{referenceNo}}</h2><p><strong>Company:</strong> {{companyName}}</p><p><strong>Contact:</strong> {{fullName}} · {{email}} · {{phone}}</p><p><strong>Country:</strong> {{country}}</p><p><strong>Interest:</strong> {{productInterest}}</p><p>{{message}}</p>",text:"New inquiry {{referenceNo}} from {{companyName}}"}});
  const newsletterTemplates=[
    {key:"newsletter_news_published_en",name:"订阅通知｜新闻发布（英文）",subject:"New from {{companyName}}: {{title}}",html:'<h2>{{title}}</h2><p>{{summary}}</p><p><a href="{{url}}">Read the full update</a></p><p><a href="{{unsubscribeUrl}}">Unsubscribe</a></p>',text:"{{title}}\n\n{{summary}}\n\n{{url}}\n\nUnsubscribe: {{unsubscribeUrl}}"},
    {key:"newsletter_news_published_zh",name:"订阅通知｜新闻发布（中文）",subject:"{{companyName}} 最新动态：{{title}}",html:'<h2>{{title}}</h2><p>{{summary}}</p><p><a href="{{url}}">查看完整动态</a></p><p><a href="{{unsubscribeUrl}}">取消订阅</a></p>',text:"{{title}}\n\n{{summary}}\n\n{{url}}\n\n取消订阅：{{unsubscribeUrl}}"},
    {key:"newsletter_product_published_en",name:"订阅通知｜新品发布（英文）",subject:"New product from {{companyName}}: {{title}}",html:'<h2>{{title}}</h2><p>{{summary}}</p><p><a href="{{url}}">View product details</a></p><p><a href="{{unsubscribeUrl}}">Unsubscribe</a></p>',text:"{{title}}\n\n{{summary}}\n\n{{url}}\n\nUnsubscribe: {{unsubscribeUrl}}"},
    {key:"newsletter_product_published_zh",name:"订阅通知｜新品发布（中文）",subject:"{{companyName}} 新品发布：{{title}}",html:'<h2>{{title}}</h2><p>{{summary}}</p><p><a href="{{url}}">查看产品详情</a></p><p><a href="{{unsubscribeUrl}}">取消订阅</a></p>',text:"{{title}}\n\n{{summary}}\n\n{{url}}\n\n取消订阅：{{unsubscribeUrl}}"},
  ];
  for(const template of newsletterTemplates)await prisma.emailTemplate.upsert({where:{key:template.key},update:{},create:template});
  const referenceDir=join(process.cwd(),"public","references");
  const mimeByExtension:Record<string,string>={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.pdf':'application/pdf'};
  for(const fileName of await readdir(referenceDir)){const extension=extname(fileName).toLowerCase();const mimeType=mimeByExtension[extension];if(!mimeType)continue;const path=`/references/${fileName}`;const existing=await prisma.media.findFirst({where:{path}});if(!existing){const info=await stat(join(referenceDir,fileName));await prisma.media.create({data:{name:`网站模板素材 - ${fileName.replace(extension,'')}`,fileName,path,mimeType,size:Number(info.size),alt:fileName.replace(extension,'').replaceAll('-',' '),folder:'website-template'}})}}
  console.log(`Seed complete. Admin: ${email} / ${password}`);
}
main().catch((error)=>{console.error(error);process.exit(1)}).finally(async()=>prisma.$disconnect());
